# Generated by Django 2.2.5 on 2019-09-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190917_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Employee_status'),
        ),
    ]
